apiVersion: v1
kind: Pod
metadata:
  name: opslab-api-image-test
  namespace: opslab
  labels:
    app.kubernetes.io/name: opslab-api
    app.kubernetes.io/instance: image-test
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: opslab-k8s
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 10

  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault

  containers:
    - name: opslab-api
      image: crpi-uxjhyltxd2kcr7f9.cn-hangzhou.personal.cr.aliyuncs.com/k8s-test-111/opslab-api@sha256:f9484afd2fe43d8b1a269572a2b8d7520d0116e0def4b240aec199561f41a32e
      imagePullPolicy: IfNotPresent

      env:
        - name: APP_NAME
          value: opslab-api
        - name: APP_VERSION
          value: v0.1.0
        - name: APP_ENV
          value: development
        - name: TMPDIR
          value: /tmp

      ports:
        - name: http
          containerPort: 8000
          protocol: TCP

      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

      startupProbe:
        httpGet:
          path: /healthz
          port: http
        periodSeconds: 2
        timeoutSeconds: 2
        failureThreshold: 30

      readinessProbe:
        httpGet:
          path: /readyz
          port: http
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3

      livenessProbe:
        httpGet:
          path: /healthz
          port: http
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 3

      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi

      volumeMounts:
        - name: tmp
          mountPath: /tmp

  volumes:
    - name: tmp
      emptyDir:
        sizeLimit: 64Mi
