apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opslab-mysqld-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: opslab-mysqld-exporter
    app.kubernetes.io/part-of: opslab-k8s
    release: opslab-monitoring
spec:
  namespaceSelector:
    matchNames:
      - opslab

  selector:
    matchLabels:
      app.kubernetes.io/name: opslab-mysqld-exporter

  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
