apiVersion: v1
kind: PersistentVolume
metadata:
  name: opslab-prometheus-local-pv
  labels:
    app.kubernetes.io/name: opslab-prometheus-storage
    app.kubernetes.io/part-of: opslab-k8s

spec:
  capacity:
    storage: 28Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: local-storage

  local:
    path: /data/prometheus

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker2
